### ISSUE TITLE
Request for default values for standard demographics

### ISSUE THREAD

**Issue by cheryldietrich** [getwilds/cancerprof#115]
For race, sex, age, setting default values might make this package quicker and easier to use for those new to the data ('All Races (includes Hispanic)', 'both sexes', 'all ages'). This would be counter to the OS of the website as it requires individual selection for all these values but might make the package more user-friendly. 

Depending on other users' requests/preferences could also consider defaulting for cancer options ('all cancer sites') and stage ('all stages').

**Comment by seankross** [comment]
Hey @cheryldietrich, we're reluctant to do this because, like the design of the website, we want users to make explicit choices for each of these values so that it is clear how the results are derived. Our compromise was to include several examples in the function documentation with different combinations of arguments that users could copy, paste, and modify.
